--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/ExampleMessages
build-by-default: true
branches:
- main
projects:
  ExampleMessages:
    path: ""
    libs:
      - src: Terpz710/messages/libMessages
        version: ^1.0.0
...
